name: Java CI with Gradle
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        java_version: ['8', '11']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java_version }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit Test
        run: |
          ./gradlew unitTest -d
